In [12]:
import pandas as pd
import sklearn

In [13]:
features = pd.read_pickle("../data/processed/features.pkl")
features

title            12 Monkeys  Air Show  All Star Sorting  Balancing Act  \
installation_id                                                          
0001e90f              False     False             False          False   
000447c4              False     False             False          False   
0006a69f               True      True              True          False   
0006c192               True     False             False           True   
0009a5a9              False     False             False          False   
...                     ...       ...               ...            ...   
fff64664              False     False             False           True   
fff70c1e              False     False             False          False   
fff744ce              False     False             False          False   
fff944d5              False     False             False          False   
fffc0583               True     False              True          False   

title            Bird Measurer (Assessment)  Bottle Filler (Activity)  \
installation_id                                                         
0001e90f                              False                     False   
000447c4                              False                     False   
0006a69f                               True                      True   
0006c192                               True                      True   
0009a5a9                              False                     False   
...                                     ...                       ...   
fff64664                              False                     False   
fff70c1e                              False                     False   
fff744ce                              False                     False   
fff944d5                              False                     False   
fffc0583                              False                     False   

title            Bubble Bath  Bug Measurer (Activity)  \
installation_id                                         
0001e90f               False                    False   
000447c4               False                    False   
0006a69f                True                     True   
0006c192                True                     True   
0009a5a9               False                    False   
...                      ...                      ...   
fff64664               False                    False   
fff70c1e               False                    False   
fff744ce               False                    False   
fff944d5               False                    False   
fffc0583               False                    False   

title            Cart Balancer (Assessment)  Cauldron Filler (Assessment)  \
installation_id                                                             
0001e90f                              False                         False   
000447c4                              False                         False   
0006a69f                              False                         False   
0006c192                              False                          True   
0009a5a9                              False                         False   
...                                     ...                           ...   
fff64664                              False                         False   
fff70c1e                              False                         False   
fff744ce                              False                         False   
fff944d5                              False                         False   
fffc0583                              False                         False   

title            ...  Rulers  Sandcastle Builder (Activity)  Scrub-A-Dub  \
installation_id  ...                                                       
0001e90f         ...   False                           True         True   
000447c4         ...   False                          False        False   
0006a69f         ...    True           

In [14]:
import numpy as np
# Labels are the values we want to predict
labels = np.array(features['Welcome to Lost Lagoon!'])
# Remove the labels from the features
# axis 1 refers to the columns
features= features.drop('Welcome to Lost Lagoon!', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

In [15]:
features

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False,  True],
       [ True, False,  True, ...,  True,  True, False]])

In [33]:
labels

array([ True,  True,  True, ...,  True,  True, False])

In [18]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [19]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)


Training Features Shape: (12750, 43)
Training Labels Shape: (12750,)
Testing Features Shape: (4250, 43)
Testing Labels Shape: (4250,)


In [22]:
# # The baseline predictions are the historical averages
# baseline_preds = test_features[:, feature_list.index('average')]
# # Baseline errors, and display average baseline error
# baseline_errors = abs(baseline_preds - test_labels)
# print('Average baseline error: ', round(np.mean(baseline_errors), 2))


In [23]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);

In [24]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)
# # Calculate the absolute errors
# errors = abs(predictions - test_labels)
# Print out the mean absolute error (mae)
# print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')


In [143]:
predictions

array([0.90683479, 0.9214532 , 0.948     , ..., 0.93173016, 0.982     ,
       0.10243333])

In [155]:
predictions_formatted=predictions.round()
labels_formatted=test_labels.round()

In [156]:
labels_formatted_pd=pd.DataFrame(data=labels_formatted,columns=[['labels']])


In [157]:
predictions_formatted_pd=pd.DataFrame(predictions_formatted,columns=[['predictions']])

In [158]:
predictions_formatted_pd

predictions
0            1.0
1            1.0
2            1.0
3            0.0
4            1.0
...          ...
4245         1.0
4246         1.0
4247         1.0
4248         1.0
4249         0.0

[4250 rows x 1 columns]

In [159]:
combined=pd.concat([predictions_formatted_pd,labels_formatted_pd],axis=1)

In [160]:
combined.columns=['predictions', 'labels']

In [161]:
combined

predictions  labels
0             1.0     1.0
1             1.0     1.0
2             1.0     1.0
3             0.0     0.0
4             1.0     1.0
...           ...     ...
4245          1.0     1.0
4246          1.0     1.0
4247          1.0     1.0
4248          1.0     1.0
4249          0.0     0.0

[4250 rows x 2 columns]

In [162]:
labels.round()

array([1., 1., 1., ..., 1., 1., 0.], dtype=float16)

In [163]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4250 entries, 0 to 4249
Data columns (total 2 columns):
predictions    4250 non-null float64
labels         4250 non-null float16
dtypes: float16(1), float64(1)
memory usage: 41.6 KB


In [164]:
combined.columns

Index(['predictions', 'labels'], dtype='object')

In [169]:
comparison=combined['predictions']==combined['labels']

In [170]:
comparison.sum()

3913

In [171]:
len(comparison)

4250